"""
Smart Robot Framework Writer with Self-Healing Capabilities

This enhanced writer converts DOM-aware test cases into Robot Framework
scripts with multiple selector strategies and self-healing features.
"""

import os
import time
from typing import Dict, List, Any, Optional
from dataclasses import asdict

try:
    from .smart_testcase_generator import SmartTestCase, TestStep
except ImportError:
    from smart_testcase_generator import SmartTestCase, TestStep

class SmartRobotWriter:
    """Enhanced Robot Framework writer with self-healing test generation"""
    
    def __init__(self, output_dir: str = "generated_tests"):
        self.output_dir = output_dir
        self.ensure_output_directory()
        
    def ensure_output_directory(self):
        """Ensure output directory exists"""
        os.makedirs(self.output_dir, exist_ok=True)
        
    def write_enhanced_tests(self, test_cases: List[SmartTestCase], filename: str = None) -> str:
        """Write enhanced test cases to Robot Framework file"""
        
        if not filename:
            timestamp = time.strftime("%Y%m%d_%H%M%S")
            filename = f"smart_tests_{timestamp}.robot"
            
        filepath = os.path.join(self.output_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            # Write file header
            self._write_header(f, test_cases)
            
            # Write settings section
            self._write_settings(f, test_cases)
            
            # Write variables section
            self._write_variables(f, test_cases)
            
            # Write keywords section (custom keywords for smart testing)
            self._write_smart_keywords(f)
            
            # Write test cases
            self._write_test_cases(f, test_cases)
            
        return filepath
    
    def _write_header(self, file_handle, test_cases: List[SmartTestCase]):
        """Write file header with metadata"""
        file_handle.write("*** Comments ***\n")
        file_handle.write("#  Smart Test Cases Generated with DOM Awareness\n")
        file_handle.write(f"#  Generated on: {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
        file_handle.write(f"#  Total Test Cases: {len(test_cases)}\n")
        file_handle.write("#  Features: Self-healing selectors, accessibility checks, performance validation\n")
        file_handle.write("#  Generated by: Smart Test Case Generator with DOM Intelligence\n")
        file_handle.write("\n")
    
    def _write_settings(self, file_handle, test_cases: List[SmartTestCase]):
        """Write settings section with required libraries"""
        file_handle.write("*** Settings ***\n")
        file_handle.write("Documentation    Smart test cases with self-healing capabilities and DOM awareness\n")
        file_handle.write("Library          SeleniumLibrary\n")
        file_handle.write("Library          Collections\n")
        file_handle.write("Library          String\n")
        file_handle.write("Library          OperatingSystem\n")
        file_handle.write("Library          DateTime\n")
        
        # Add accessibility library if accessibility tests are present
        accessibility_tests = [tc for tc in test_cases if any('accessibility' in tag for tag in tc.tags)]
        if accessibility_tests:
            file_handle.write("Library          axe_selenium_python.Axe\n")
        
        # Add performance testing library if performance thresholds are set
        perf_tests = [tc for tc in test_cases if tc.performance_thresholds]
        if perf_tests:
            file_handle.write("Library          RequestsLibrary\n")
        
        file_handle.write("\n")
        file_handle.write("Suite Setup      Smart Test Suite Setup\n")
        file_handle.write("Suite Teardown   Smart Test Suite Teardown\n")
        file_handle.write("Test Setup       Smart Test Setup\n")
        file_handle.write("Test Teardown    Smart Test Teardown\n")
        file_handle.write("\n")
    
    def _write_variables(self, file_handle, test_cases: List[SmartTestCase]):
        """Write variables section with test data and configuration"""
        file_handle.write("*** Variables ***\n")
        file_handle.write("${BASE_URL}                  https://example.com\n")
        file_handle.write("${BROWSER}                   Chrome\n")
        file_handle.write("${TIMEOUT}                   30s\n")
        file_handle.write("${IMPLICIT_WAIT}            10s\n")
        file_handle.write("${SCREENSHOT_DIR}           screenshots\n")
        file_handle.write("${SELF_HEALING_ENABLED}     True\n")
        file_handle.write("${MAX_HEALING_ATTEMPTS}     3\n")
        file_handle.write("${SELECTOR_TIMEOUT}         5s\n")
        
        # Add test data variables
        file_handle.write("\n# Test Data Variables\n")
        file_handle.write("${VALID_USERNAME}           testuser@example.com\n")
        file_handle.write("${VALID_PASSWORD}           TestPassword123!\n")
        file_handle.write("${INVALID_USERNAME}         invalid@example.com\n")
        file_handle.write("${INVALID_PASSWORD}         wrongpassword\n")
        
        # Add performance threshold variables
        perf_tests = [tc for tc in test_cases if tc.performance_thresholds]
        if perf_tests:
            file_handle.write("\n# Performance Thresholds\n")
            file_handle.write("${MAX_PAGE_LOAD_TIME}       3.0\n")
            file_handle.write("${MAX_LOGIN_TIME}           3.0\n")
            file_handle.write("${MAX_SEARCH_TIME}          2.0\n")
        
        file_handle.write("\n")
    
    def _write_smart_keywords(self, file_handle):
        """Write custom smart testing keywords"""
        file_handle.write("*** Keywords ***\n")
        
        # Suite setup/teardown keywords
        file_handle.write("Smart Test Suite Setup\n")
        file_handle.write("    [Documentation]    Setup for smart test suite with self-healing capabilities\n")
        file_handle.write("    Set Global Variable    ${SUITE_START_TIME}    ${EMPTY}\n")
        file_handle.write("    ${start_time}=    Get Current Date    result_format=epoch\n")
        file_handle.write("    Set Global Variable    ${SUITE_START_TIME}    ${start_time}\n")
        file_handle.write("    Create Directory    ${SCREENSHOT_DIR}\n")
        file_handle.write("    Log    Smart test suite initialized with self-healing enabled: ${SELF_HEALING_ENABLED}\n")
        file_handle.write("\n")
        
        file_handle.write("Smart Test Suite Teardown\n")
        file_handle.write("    [Documentation]    Teardown for smart test suite\n")
        file_handle.write("    Close All Browsers\n")
        file_handle.write("    ${end_time}=    Get Current Date    result_format=epoch\n")
        file_handle.write("    ${duration}=    Evaluate    ${end_time} - ${SUITE_START_TIME}\n")
        file_handle.write("    Log    Total suite execution time: ${duration} seconds\n")
        file_handle.write("\n")
        
        # Test setup/teardown keywords
        file_handle.write("Smart Test Setup\n")
        file_handle.write("    [Documentation]    Setup for individual smart test\n")
        file_handle.write("    ${test_start_time}=    Get Current Date    result_format=epoch\n")
        file_handle.write("    Set Test Variable    ${TEST_START_TIME}    ${test_start_time}\n")
        file_handle.write("    Set Test Variable    ${HEALING_ATTEMPTS}    0\n")
        file_handle.write("\n")
        
        file_handle.write("Smart Test Teardown\n")
        file_handle.write("    [Documentation]    Teardown for individual smart test\n")
        file_handle.write("    Run Keyword If    '${TEST STATUS}' == 'FAIL'    Capture Page Screenshot    ${SCREENSHOT_DIR}/failed_${TEST NAME}_${SUITE_NAME}.png\n")
        file_handle.write("    ${test_end_time}=    Get Current Date    result_format=epoch\n")
        file_handle.write("    ${test_duration}=    Evaluate    ${test_end_time} - ${TEST_START_TIME}\n")
        file_handle.write("    Log    Test execution time: ${test_duration} seconds\n")
        file_handle.write("    Log    Self-healing attempts used: ${HEALING_ATTEMPTS}\n")
        file_handle.write("\n")
        
        # Smart element interaction keywords
        file_handle.write("Smart Click Element\n")
        file_handle.write("    [Documentation]    Click element with self-healing selector strategy\n")
        file_handle.write("    [Arguments]    @{selectors}\n")
        file_handle.write("    ${element_found}=    Smart Find Element    @{selectors}\n")
        file_handle.write("    Run Keyword If    ${element_found}    Click Element    ${FOUND_SELECTOR}\n")
        file_handle.write("    Run Keyword Unless    ${element_found}    Fail    Could not find element with any of the provided selectors\n")
        file_handle.write("\n")
        
        file_handle.write("Smart Input Text\n")
        file_handle.write("    [Documentation]    Input text with self-healing selector strategy\n")
        file_handle.write("    [Arguments]    ${text}    @{selectors}\n")
        file_handle.write("    ${element_found}=    Smart Find Element    @{selectors}\n")
        file_handle.write("    Run Keyword If    ${element_found}    Input Text    ${FOUND_SELECTOR}    ${text}\n")
        file_handle.write("    Run Keyword Unless    ${element_found}    Fail    Could not find input element with any of the provided selectors\n")
        file_handle.write("\n")
        
        file_handle.write("Smart Find Element\n")
        file_handle.write("    [Documentation]    Find element using multiple selector strategies with self-healing\n")
        file_handle.write("    [Arguments]    @{selectors}\n")
        file_handle.write("    Set Test Variable    ${FOUND_SELECTOR}    ${EMPTY}\n")
        file_handle.write("    FOR    ${selector}    IN    @{selectors}\n")
        file_handle.write("        ${element_exists}=    Run Keyword And Return Status    Wait Until Element Is Visible    ${selector}    ${SELECTOR_TIMEOUT}\n")
        file_handle.write("        Run Keyword If    ${element_exists}    Set Test Variable    ${FOUND_SELECTOR}    ${selector}\n")
        file_handle.write("        Run Keyword If    ${element_exists}    Return From Keyword    ${True}\n")
        file_handle.write("    END\n")
        file_handle.write("    \n")
        file_handle.write("    # If no selector worked, try self-healing if enabled\n")
        file_handle.write("    Run Keyword If    '${SELF_HEALING_ENABLED}' == 'True' and ${HEALING_ATTEMPTS} < ${MAX_HEALING_ATTEMPTS}\n")
        file_handle.write("    ...    Attempt Self Healing    @{selectors}\n")
        file_handle.write("    Return From Keyword    ${False}\n")
        file_handle.write("\n")
        
        file_handle.write("Attempt Self Healing\n")
        file_handle.write("    [Documentation]    Attempt to heal broken selectors using alternative strategies\n")
        file_handle.write("    [Arguments]    @{original_selectors}\n")
        file_handle.write("    ${healing_attempts}=    Evaluate    ${HEALING_ATTEMPTS} + 1\n")
        file_handle.write("    Set Test Variable    ${HEALING_ATTEMPTS}    ${healing_attempts}\n")
        file_handle.write("    Log    Attempting self-healing for selectors: ${original_selectors}\n")
        file_handle.write("    \n")
        file_handle.write("    # Try visual-based healing (placeholder - would need computer vision)\n")
        file_handle.write("    # Try DOM structure-based healing\n")
        file_handle.write("    # Try similarity-based healing\n")
        file_handle.write("    \n")
        file_handle.write("    Log    Self-healing attempt ${healing_attempts} completed\n")
        file_handle.write("\n")
        
        # Accessibility testing keywords
        file_handle.write("Check Accessibility\n")
        file_handle.write("    [Documentation]    Perform accessibility checks on current page\n")
        file_handle.write("    [Arguments]    ${wcag_level}=AA\n")
        file_handle.write("    ${accessibility_violations}=    Run Keyword And Return Status    Execute Javascript    return axe.run()\n")
        file_handle.write("    Log    Accessibility check completed for WCAG ${wcag_level}\n")
        file_handle.write("    # Additional accessibility validation would go here\n")
        file_handle.write("\n")
        
        file_handle.write("Verify Keyboard Navigation\n")
        file_handle.write("    [Documentation]    Verify keyboard navigation through page elements\n")
        file_handle.write("    [Arguments]    @{elements}\n")
        file_handle.write("    FOR    ${element}    IN    @{elements}\n")
        file_handle.write("        Press Keys    None    TAB\n")
        file_handle.write("        ${focused_element}=    Execute Javascript    return document.activeElement\n")
        file_handle.write("        # Verify focus is on expected element\n")
        file_handle.write("    END\n")
        file_handle.write("\n")
        
        # Performance validation keywords
        file_handle.write("Measure Page Load Time\n")
        file_handle.write("    [Documentation]    Measure and validate page load time\n")
        file_handle.write("    [Arguments]    ${max_time}=3.0\n")
        file_handle.write("    ${load_start}=    Get Current Date    result_format=epoch\n")
        file_handle.write("    Wait Until Page Contains Element    body    ${TIMEOUT}\n")
        file_handle.write("    ${load_end}=    Get Current Date    result_format=epoch\n")
        file_handle.write("    ${load_time}=    Evaluate    ${load_end} - ${load_start}\n")
        file_handle.write("    Should Be True    ${load_time} <= ${max_time}    Page load time ${load_time}s exceeded maximum ${max_time}s\n")
        file_handle.write("    Log    Page loaded in ${load_time} seconds\n")
        file_handle.write("    [Return]    ${load_time}\n")
        file_handle.write("\n")
        
        # Visual validation keywords
        file_handle.write("Take Smart Screenshot\n")
        file_handle.write("    [Documentation]    Take screenshot with smart naming and validation\n")
        file_handle.write("    [Arguments]    ${checkpoint_name}\n")
        file_handle.write("    ${timestamp}=    Get Current Date    result_format=%Y%m%d_%H%M%S\n")
        file_handle.write("    ${screenshot_path}=    Set Variable    ${SCREENSHOT_DIR}/${checkpoint_name}_${timestamp}.png\n")
        file_handle.write("    Capture Page Screenshot    ${screenshot_path}\n")
        file_handle.write("    Log    Screenshot captured: ${screenshot_path}\n")
        file_handle.write("    [Return]    ${screenshot_path}\n")
        file_handle.write("\n")
    
    def _write_test_cases(self, file_handle, test_cases: List[SmartTestCase]):
        """Write all test cases"""
        file_handle.write("*** Test Cases ***\n")
        
        for test_case in test_cases:
            self._write_single_test_case(file_handle, test_case)
            file_handle.write("\n")
    
    def _write_single_test_case(self, file_handle, test_case: SmartTestCase):
        """Write a single test case"""
        file_handle.write(f"{test_case.name}\n")
        file_handle.write(f"    [Documentation]    {test_case.description}\n")
        
        # Write tags
        if test_case.tags:
            tags_str = "    ".join(test_case.tags)
            file_handle.write(f"    [Tags]    {tags_str}\n")
        
        # Write setup steps
        if test_case.setup_steps:
            file_handle.write("    [Setup]    Run Keywords\n")
            for step in test_case.setup_steps:
                self._write_test_step(file_handle, step, indent="    ...    ")
        
        # Write teardown steps
        if test_case.teardown_steps:
            file_handle.write("    [Teardown]    Run Keywords\n")
            for step in test_case.teardown_steps:
                self._write_test_step(file_handle, step, indent="    ...    ")
        
        # Write performance threshold if specified
        if test_case.performance_thresholds:
            file_handle.write("    # Performance validation\n")
            for metric, threshold in test_case.performance_thresholds.items():
                file_handle.write(f"    Set Test Variable    ${{MAX_{metric.upper()}}}    {threshold}\n")
        
        # Write main test steps
        file_handle.write("    \n")
        file_handle.write("    # Test execution steps\n")
        for i, step in enumerate(test_case.test_steps, 1):
            file_handle.write(f"    # Step {i}: {step.description}\n")
            self._write_test_step(file_handle, step)
            
            # Add screenshot checkpoint if specified
            if step.screenshot_checkpoint:
                file_handle.write(f"    Take Smart Screenshot    step_{i}_{step.action}\n")
        
        # Write data variations if present
        if test_case.data_variations:
            file_handle.write("    \n")
            file_handle.write("    # Data-driven test variations\n")
            for i, variation in enumerate(test_case.data_variations[:3], 1):  # Limit to 3 variations
                file_handle.write(f"    Log    Testing with data set {i}: {variation}\n")
        
        # Write expected results validation
        if test_case.expected_results:
            file_handle.write("    \n")
            file_handle.write("    # Validate expected results\n")
            for result in test_case.expected_results:
                file_handle.write(f"    Log    Expected result: {result}\n")
        
        # Write reliability score as comment
        file_handle.write(f"    \n")
        file_handle.write(f"    # Test reliability score: {test_case.reliability_score:.2f}\n")
        file_handle.write(f"    # Self-healing enabled: {test_case.self_healing_enabled}\n")
    
    def _write_test_step(self, file_handle, step: TestStep, indent="    "):
        """Write a single test step"""
        if step.action == "navigate_to_page":
            file_handle.write(f"{indent}Open Browser    {step.value or '${BASE_URL}'}    ${{BROWSER}}\n")
            file_handle.write(f"{indent}Maximize Browser Window\n")
            if step.wait_conditions:
                for condition in step.wait_conditions:
                    if condition == "page_loaded":
                        file_handle.write(f"{indent}Wait Until Page Contains Element    body    ${{TIMEOUT}}\n")
        
        elif step.action == "fill_field":
            selectors_str = self._format_selectors_for_robot(step.element_selectors + step.fallback_selectors)
            file_handle.write(f"{indent}Smart Input Text    {step.value}    {selectors_str}\n")
        
        elif step.action == "click_element":
            selectors_str = self._format_selectors_for_robot(step.element_selectors + step.fallback_selectors)
            file_handle.write(f"{indent}Smart Click Element    {selectors_str}\n")
        
        elif step.action == "wait_for_element":
            if step.element_selectors:
                primary_selector = step.element_selectors[0]
                file_handle.write(f"{indent}Wait Until Element Is Visible    {primary_selector}    ${{TIMEOUT}}\n")
        
        elif step.action == "verify_result":
            if step.validation_points:
                for validation in step.validation_points:
                    if "visible" in validation:
                        if step.element_selectors:
                            file_handle.write(f"{indent}Wait Until Element Is Visible    {step.element_selectors[0]}    ${{TIMEOUT}}\n")
        
        elif step.action == "test_keyboard_navigation":
            if step.accessibility_checks:
                file_handle.write(f"{indent}Verify Keyboard Navigation    {self._format_selectors_for_robot(step.element_selectors)}\n")
        
        elif step.action == "verify_aria_labels":
            if step.accessibility_checks:
                file_handle.write(f"{indent}Check Accessibility    AA\n")
        
        elif step.action == "verify_color_contrast":
            if step.accessibility_checks:
                file_handle.write(f"{indent}Check Accessibility    AA\n")
        
        elif step.action == "take_screenshot":
            file_handle.write(f"{indent}Take Smart Screenshot    {step.description.replace(' ', '_')}\n")
        
        elif step.action == "cleanup_browser_data":
            file_handle.write(f"{indent}Delete All Cookies\n")
        
        elif step.action == "cleanup":
            file_handle.write(f"{indent}Close Browser\n")
        
        else:
            # Generic step handling
            file_handle.write(f"{indent}Log    Executing: {step.description}\n")
        
        # Add wait conditions
        for condition in step.wait_conditions:
            if condition == "element_visible" and step.element_selectors:
                file_handle.write(f"{indent}Wait Until Element Is Visible    {step.element_selectors[0]}    ${{SELECTOR_TIMEOUT}}\n")
            elif condition == "element_clickable" and step.element_selectors:
                file_handle.write(f"{indent}Wait Until Element Is Enabled    {step.element_selectors[0]}    ${{SELECTOR_TIMEOUT}}\n")
    
    def _format_selectors_for_robot(self, selectors: List[str]) -> str:
        """Format selectors for Robot Framework arguments"""
        if not selectors:
            return ""
        
        # Clean and format selectors
        formatted_selectors = []
        for selector in selectors[:5]:  # Limit to 5 selectors
            # Escape special characters for Robot Framework
            clean_selector = selector.replace("'", "\\'").replace('"', '\\"')
            formatted_selectors.append(clean_selector)
        
        return "    ".join(formatted_selectors)
    
    def generate_data_driven_tests(self, test_cases: List[SmartTestCase], filename: str = None) -> str:
        """Generate data-driven test file using template approach"""
        if not filename:
            timestamp = time.strftime("%Y%m%d_%H%M%S")
            filename = f"data_driven_tests_{timestamp}.robot"
            
        filepath = os.path.join(self.output_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write("*** Settings ***\n")
            f.write("Documentation    Data-driven smart tests with multiple variations\n")
            f.write("Library          SeleniumLibrary\n")
            f.write("Test Template    Execute Data Driven Test\n")
            f.write("\n")
            
            f.write("*** Variables ***\n")
            f.write("${BASE_URL}    https://example.com\n")
            f.write("${BROWSER}     Chrome\n")
            f.write("\n")
            
            f.write("*** Test Cases ***\n")
            f.write("# Test Case Name                    Test Data\n")
            
            for test_case in test_cases:
                if test_case.data_variations:
                    for i, variation in enumerate(test_case.data_variations, 1):
                        variation_name = f"{test_case.name} - Variation {i}"
                        variation_data = "    ".join([f"{k}:{v}" for k, v in variation.items()])
                        f.write(f"{variation_name}    {variation_data}\n")
            
            f.write("\n")
            f.write("*** Keywords ***\n")
            f.write("Execute Data Driven Test\n")
            f.write("    [Arguments]    ${test_data}\n")
            f.write("    Log    Executing test with data: ${test_data}\n")
            f.write("    # Template implementation would go here\n")
        
        return filepath
    
    def generate_test_summary_report(self, test_cases: List[SmartTestCase]) -> str:
        """Generate summary report of generated tests"""
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        report_path = os.path.join(self.output_dir, f"test_summary_{timestamp}.txt")
        
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write("SMART TEST GENERATION SUMMARY REPORT\n")
            f.write("=" * 50 + "\n\n")
            f.write(f"Generated on: {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"Total test cases generated: {len(test_cases)}\n\n")
            
            # Statistics by tag
            tag_counts = {}
            for test_case in test_cases:
                for tag in test_case.tags:
                    tag_counts[tag] = tag_counts.get(tag, 0) + 1
            
            f.write("Test Distribution by Tags:\n")
            for tag, count in sorted(tag_counts.items()):
                f.write(f"  {tag}: {count} tests\n")
            f.write("\n")
            
            # Reliability statistics
            reliability_scores = [tc.reliability_score for tc in test_cases]
            avg_reliability = sum(reliability_scores) / len(reliability_scores) if reliability_scores else 0
            
            f.write(f"Average Reliability Score: {avg_reliability:.2f}\n")
            f.write(f"Self-healing enabled tests: {sum(1 for tc in test_cases if tc.self_healing_enabled)}\n")
            f.write(f"Tests with accessibility checks: {sum(1 for tc in test_cases if any('accessibility' in tag for tag in tc.tags))}\n")
            f.write(f"Tests with performance thresholds: {sum(1 for tc in test_cases if tc.performance_thresholds)}\n")
            f.write("\n")
            
            # Individual test details
            f.write("INDIVIDUAL TEST DETAILS:\n")
            f.write("-" * 30 + "\n")
            for test_case in test_cases:
                f.write(f"\nTest ID: {test_case.test_id}\n")
                f.write(f"Name: {test_case.name}\n")
                f.write(f"Description: {test_case.description}\n")
                f.write(f"Tags: {', '.join(test_case.tags)}\n")
                f.write(f"Reliability Score: {test_case.reliability_score:.2f}\n")
                f.write(f"Test Steps: {len(test_case.test_steps)}\n")
                f.write(f"Data Variations: {len(test_case.data_variations)}\n")
                if test_case.ui_patterns_used:
                    f.write(f"UI Patterns: {', '.join(test_case.ui_patterns_used)}\n")
                f.write("\n")
        
        return report_path